name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install npm
        run: npm install

      - name: Clean Gradle cache
        run: rm -rf ~/.gradle/caches

      - name: Build APK
        run: cd android && chmod +x gradlew && ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SannaBot-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
